language: python

python:
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - pytest -v --cov=bplustree tests/
    - pep8 bplustree tests

after_success:
  - coveralls

notifications:
    email: false
